### PR TITLE
Fixed tooltip layout issues for low barrel and stacked bar

### LINKED ISSUE #937: Low barrel example chart throws lots of errors
Errors occur on mouse move and on zoom.

image

 Possibly something to do with the broken date labels below.

image

### PR DESCRIPTION
**Pull request by jdhodges**
Closes #937.

### CODE REVIEW

File: src/layout/strategy/boundingBox.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ export default function() {
             if (ty + d.height > bounds[1]) {
                 ty -= d.height;
             }
-            return {x: tx, y: ty};
+            return {height: d.height, width: d.width, x: tx, y: ty};
```
Comment (ColinEberhardt) [inline src/layout/strategy/boundingBox.js]: This code is now in the following project: https://github.com/d3fc/d3fc-label-layout/blob/master/src/boundingBox.js

Would you mind applying this fix there?

**Comment by jdhodges** [comment]
Sorry for the delay, I've made updates to this and https://github.com/d3fc/d3fc-label-layout/pull/3 :grinning:
