### PR TITLE
Stack bar fix

### LINKED ISSUE #623: Stacked bar broken on website
.... gives me something to do on the flight home ...

### PR DESCRIPTION
**Pull request by ColinEberhardt**
Fixes #623 

The issue was with `xyBase` which changed the 'defined' rules to be strictly numeric.

I've also re-instated 0.5 opacity for bollinger fill, however rather than making all area series 0.5 opacity, this is now just applied to bollinger.

### CODE REVIEW

File: src/series/xyBase.js [hunk 1]
```diff
@@ -24,8 +24,8 @@ export default function() {
         return yScale(yValue(d, i));
     };
     base.defined = function(d, i) {
-        return !isNaN(x0Value(d, i)) && !isNaN(y0Value(d, i)) &&
```
Comment (chrisprice) [inline src/series/xyBase.js]: Worth using `==`?

Comment (ColinEberhardt) [inline src/series/xyBase.js]: Yeah - fair point. Changed to `!= null` to allow for undefined and null for 'undefined' values.

**Comment by chrisprice** [comment]
:+1:
